language: cpp
compiler:
  - clang
install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev liblas-dev
  # from https://github.com/travis-ci/travis-ci/issues/979.
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
script:
  - echo "CXX="$CXX
  - echo "CC="$CC
  # First, using c++03.
  # Specify that we do not use 11, since
  # the default for this variable may change soon.
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF -DSIMBODY_STANDARD_11=ON -DCMAKE_CXX_FLAGS=-Werror
  # Check which compiler and compiler version we're using.
  - make -j8
  - ctest -j8 
