language: cpp
env:
  - ELEVEN=ON
  - ELEVEN=OFF
compiler:
  - gcc
  - clang
install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev liblas-dev
  # from https://github.com/travis-ci/travis-ci/issues/979.
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  # Check which compiler and compiler version we're using.
  - echo "CXX="$CXX
  - echo "CC="$CC
  # Configure and generate Makefiles.
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF -DSIMBODY_STANDARD_11=$ELEVEN -DCMAKE_CXX_FLAGS=-Werror
  # Build.
  - make -j8
script:
  - ctest -j8
