language: cpp
env:
  - ELEVEN=ON
compiler:
  - clang
before_install:
  - wget http://llvm.org/releases/3.4.1/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz
  - tar xJf clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz
  - export PATH=$PWD/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04/bin:$PATH
install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev
  # Check which compiler and compiler version we're using.
  - echo "CXX="$CXX
  - echo "CC="$CC
  # Configure and generate Makefiles.
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF -DCMAKE_CXX_FLAGS="-Werror -std=c++11" -DCMAKE_VERBOSE_MAKEFILE=on -DCMAKE_BUILD_TYPE=Debug
  # Build.
  - make -j8
script:
  - ctest -R '(BNTTest|TestScalar)' -V
