language: cpp
env:
  - ELEVEN=ON
compiler:
  - clang
install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev liblas-dev
  # Check which compiler and compiler version we're using.
  - echo "CXX="$CXX
  - echo "CC="$CC
  # Configure and generate Makefiles.
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF -DSIMBODY_STANDARD_11=$ELEVEN -DCMAKE_CXX_FLAGS=-Werror
  # Build.
  - make -j8
script:
  - ctest -R '(BNTTest|TestScalar)' -V
