language: cpp
env:
  - ELEVEN=ON
compiler:
  - clang
install:
  - sudo apt-get update
  - sudo apt-get install liblapack-dev
  # Check which compiler and compiler version we're using.
  - echo "CXX="$CXX
  - echo "CC="$CC
  # Configure and generate Makefiles.
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF -DCMAKE_CXX_FLAGS="-std=c++11 -stdlib=libc++" -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_VERBOSE_MAKEFILE=on
  # Build.
  - make -j8
script:
  - ctest -R '(BNTTest|TestScalar)' -V
