# This script is used by the Travis-CI (continuous integration) testing
# framework to run Simbody's tests with every GitHub push or pull-request.
language: cpp

env:
  # Each line is a separate build in the build matrix. A build in the build
  # matrix is defined by the environment variables defined on the line, which
  # should be space-delimited. For example,
  # - ABC=ON DEF=OFF GHI=ON
  - CPP11=ON BTYPE=Release

compiler:
  - clang

before_install:
  ## Dependencies for Simbody.
  - sudo apt-get update
  - sudo apt-get install liblapack-dev

  ## C++11 and gcc. Update to gcc 4.8, which provides full C++11 support.
  ## We use this script because if building Simbody with C++11, we need
  ## gcc-4.8, and the Travis Ubuntu 12.04 machines have an older version of gcc.
  ## See https://github.com/travis-ci/travis-ci/issues/979.
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8" CC="gcc-4.8"

  ## Clang 3.4 has bugfixes.
  - if [ "$CXX" = "clang++" ]; then wget http://llvm.org/releases/3.4.1/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" = "clang++" ]; then tar xJf clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04.tar.xz; fi
  - if [ "$CXX" = "clang++" ]; then export PATH=$PWD/clang+llvm-3.4.1-x86_64-unknown-ubuntu12.04/bin:$PATH; fi


install:
  - cmake . -DBUILD_VISUALIZER=OFF -DSIMBODY_STANDARD_11=$CPP11 -DCMAKE_BUILD_TYPE=$BTYPE -DCMAKE_CXX_FLAGS=-Werror
  - make -j8

script:
  - ctest -R TestCollisionDetectionAlgorithm -V
