# This script is used by the Travis-CI (continuous integration) testing
# framework to run Simbody's tests with every GitHub push or pull-request.
language: cpp

sudo: false

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - liblapack-dev
      - freeglut3-dev
      - libxi-dev
      - libxmu-dev

env:
  # Each line is a separate build in the build matrix. A build in the build
  # matrix is defined by the environment variables defined on the line, which
  # should be space-delimited. For example,
  # - ABC=ON DEF=OFF GHI=ON
  # Simbody 3.6 and up requires c++11
  - BTYPE=Release

before_install:
  ## Ensure that there are no tabs in source code.
  # GREP returns 0 (true) if there are any matches, and
  # we don't want any matches. If there are matches,
  # print a helpful message, and make the test fail by using "false".
  # The GREP command here checks for any tab characters in the the files
  # that match the specified pattern. GREP does not pick up explicit tabs
  # (e.g., literally a \t in a source file).
  # This grep command is invalid on osx.
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then if grep --recursive --include={*.cpp,*.c,*.h,*.md,*.yml,*.cmake.*.xml,*.html,*.in,*.txt} -P "\t" . ; then echo "Tabs found in the lines shown above. See CONTRIBUTING.md about tabs."; false; else echo "Repo passed no-tabs check."; fi; else echo "No-tabs check not performed."; fi

  - mkdir $HOME/cmake-install
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.sh
  - sh cmake-3.2.1-Linux-x86_64.sh --skip-license --prefix=$HOME/cmake-install
  - set PATH=$HOME/cmake-install:$PATH

before_script:
  - mkdir ~/simbody-build && cd ~/simbody-build
  # Configure.
  - $HOME/cmake-install/bin/cmake $TRAVIS_BUILD_DIR -DCMAKE_BUILD_TYPE=$BTYPE -DCMAKE_CXX_FLAGS=-Werror -DCMAKE_INSTALL_PREFIX=$HOME/simbody-install
  # Build.
  - make -j8

script:
  ## Test Simbody.
  - $HOME/cmake-install/bin/ctest -j8 --output-on-failure

  ## Make sure we can install with no issues.
  - make -j8 install
