language: cpp
env: 
  global: 
    secure: Q+rdj1WCDeGHYcJtRGcKypo5L8qIDUQSITnfctVS0O3o70QVG+bAmtTdXaTP9H+ICLisqhm8FRQ9Kk34hA51RyAitj77UUDOqj8V5kQfpOvHhR7RSvf3AJYjbAeo0CPw8cRJDN2OF6R7AApdhyjRzZS5Nl63pNWWjY4p6KFkw2Q=
compiler: 
- gcc
- clang
install: 
- sudo apt-get update
- sudo apt-get install liblapack-dev liblas-dev
- sudo apt-get --no-install-recommends install doxygen
- cmake . -DBUILD_EXAMPLES=off -DBUILD_VISUALIZER=off
script: true
after_success:
    echo -e "Starting to update gh-pages.\n"
    make doxygen
    cp -R html $HOME/html
    rm -rf .
    git checkout -b gh-pages origin/gh-pages
    mv $HOME/html/ .
    git config --global user.email "traivs@travis-ci.org"
    git config --global user.name "Travis"
    git add -f .
    git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to gh-pages."
    git push -fq origin gh-pages > /dev/null
    echo -e "Done updating gh-pages.\n"
