# Windows testing using Visual Studio.

# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

shallow_clone: true

init:
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%

build_script:
  # Treat all warnings as errors.
  - cmake . -DBUILD_VISUALIZER=OFF -DCMAKE_INSTALL_PREFIX=install
  # See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
  # command-line options to MSBuild.
  - MSBuild Simbody.sln /maxcpucount /target:ALL_BUILD /p:Configuration=Release /verbosity:quiet

test_script:
  - ctest -j8 -C Release --output-on-failure
    
after_test:
  ## Install Simbody.
  - cmake --build . --target install --config Release -- /maxcpucount /verbosity:quiet

  ## Create NuGet package.
  # Create a nupkg. The install directory is to be packaged.
  - nuget pack simbody.nuspec -BasePath install
  # The line above creates the file simbody.0.0.0.nupkg.
  # Push this to Appveyor's NuGet account feed, to be used by OpenSim.
  - appveyor PushArtifact simbody.0.0.0.nupkg
