# Syntax for this file:
# http://www.appveyor.com/docs/appveyor-yml

install:
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - cmake . -DBUILD_EXAMPLES=ON -DBUILD_VISUALIZER=OFF
  # See http://msdn.microsoft.com/en-us/library/ms164311.aspx for
  # command-line options to MSBuild.
  - MSBuild Simbody.sln /m /p:Configuration=Release

build: OFF

test: OFF

test_script:
  - MSBuild Simbody.sln /m /target:RUN_TESTS_PARALLEL /p:Configuration=Release

deploy: OFF
